set_moisture:
  name: Set moisture
  description: Force the moisture value to a particular zone, a way to provide Netro with the value of an external sensor
  fields:
    zone_id:
      name: Zone
      description: The zone whose moisture should be set (please select among zone devices only)
      required: true
      selector:
        device:
          integration: netro_watering
    moisture:
      name: Moisture
      description: The humidity value to be set to the zone (in %)
      required: true
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
start_watering:
  name: Start watering
  description: Start watering for a specified duration, delay before start, or start time and date
  target:
    entity:
      integration: netro_watering
      domain: switch
  fields:
    duration:
      name: Duration
      description: Duration of activation of this sprinkler
      required: true
      default: 30
      selector:
        number:
          min: 1
          max: 90
          unit_of_measurement: "minutes"
    delay:
      name: Delay
      description: Waiting time before starting watering
      required: false
      selector:
        number:
          min: 0
          max: 90
          unit_of_measurement: "minutes"
    start_time:
      name: Start time
      description: Watering start date and time
      required: false
      selector:
        datetime:
stop_watering:
  name: Stop watering
  description: Stop watering all zones at once or a specific zone
  target:
    entity:
      integration: netro_watering
      domain: switch
enable:
  name: Enable
  description: Enable the selected controller
  target:
    entity:
      integration: netro_watering
      domain: switch
disable:
  name: Disable
  description: Disable the selected controller
  target:
    entity:
      integration: netro_watering
      domain: switch
