refresh_data:
  name: Refresh data
  description: Refresh data of Netro devices (controller, zone, sensors)
  fields:
    config_entry_id:
      name: Config entry
      description: The configuration entry whose devices to be refreshed are referring to
      required: true
      selector:
        config_entry:
          integration: netro_watering
report_weather:
  name: Report weather
  description: This is for reporting weather data, overriding system default weather data
  fields:
    config_entry_id:
      name: Config entry
      description: The configuration entry whose weather data should be reported
      required: true
      selector:
        config_entry:
          integration: netro_watering
    date:
      name: Date
      description: Weather date, can not be earlier than yesterday
      required: true
      selector:
        date:
    condition:
      name: Condition
      description: Weather condition
      required: false
      selector:
        select:
          options:
            - clear
            - cloudy
            - rain
            - snow
            - wind
    rain:
      name: Rain
      description: Rain fall amount (floating value in mm)
      required: false
      selector:
        number:
          min: 0
          max: 500
          step: 0.01
          mode: box
          unit_of_measurement: "mm"
    rain_prob:
      name: Rain probability
      description: Rainfall probability, in the range of [0,100]
      required: false
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
    temp:
      name: Temperature
      description: Average temperature, Celsius temperature
      required: false
      selector:
        number:
          min: 0
          max: 60
          step: 0.1
          unit_of_measurement: "째C"
    t_min:
      name: Minimum temperature
      description: Minimum temperature, Celsius temperature
      required: false
      selector:
        number:
          min: 0
          max: 60
          step: 0.1
          unit_of_measurement: "째C"
    t_max:
      name: Maximum temperature
      description: Maximum temperature, Celsius temperature
      required: false
      selector:
        number:
          min: 0
          max: 60
          step: 0.1
          unit_of_measurement: "째C"
    t_dew:
      name: Dew temperature
      description: Dew point temperature, Celsius temperature
      required: false
      selector:
        number:
          min: 0
          max: 60
          step: 0.1
          unit_of_measurement: "째C"
    wind_speed:
      name: Wind speed
      description: Wind speed, unit of m/s
      required: false
      selector:
        number:
          min: 0
          max: 60
          step: 0.01
          unit_of_measurement: "m/s"
    humidity:
      name: Humidity
      description: Humidity, in the range of [0,100]
      required: false
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
    pressure:
      name: Pressure
      description: Air pressure, in the unit of hpa
      required: false
      selector:
        number:
          min: 850
          max: 1100
          step: 0.1
          unit_of_measurement: "hpa"
          mode: box
set_moisture:
  name: Set moisture
  description: Set moisture value to a given zone, a way to provide Netro with the value of an external sensor
  fields:
    zone_id:
      name: Zone
      description: The zone whose moisture should be set
      required: true
      selector:
        device:
          integration: netro_watering
          filter:
            model: Virtual zone
    moisture:
      name: Moisture
      description: The humidity value to be set to the zone (in %)
      required: true
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
start_watering:
  name: Start watering
  description: Start watering for a specified duration, delay before start, or start time and date
  target:
    entity:
      integration: netro_watering
      domain: switch
  fields:
    duration:
      name: Duration
      description: Duration of activation of this sprinkler
      required: true
      default: 30
      selector:
        number:
          min: 1
          max: 90
          unit_of_measurement: "minutes"
    delay:
      name: Delay
      description: Waiting time before starting watering
      required: false
      selector:
        number:
          min: 0
          max: 90
          unit_of_measurement: "minutes"
    start_time:
      name: Start time
      description: Watering start date and time
      required: false
      selector:
        datetime:
stop_watering:
  name: Stop watering
  description: Stop watering all zones at once or a specific zone
  target:
    entity:
      integration: netro_watering
      domain: switch
enable:
  name: Enable
  description: Enable the selected controller
  target:
    entity:
      integration: netro_watering
      domain: switch
disable:
  name: Disable
  description: Disable the selected controller
  target:
    entity:
      integration: netro_watering
      domain: switch
